SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `address`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `film`;
DROP TABLE IF EXISTS `shop`;
DROP TABLE IF EXISTS `dvd`;
DROP TABLE IF EXISTS `reserve`;
DROP TABLE IF EXISTS `rental`;
DROP TABLE IF EXISTS `payment`;
DROP TABLE IF EXISTS `actor`;
DROP TABLE IF EXISTS `plays`;
DROP TABLE IF EXISTS `category`;
DROP TABLE IF EXISTS `language`;
DROP TABLE IF EXISTS `film_category`;
DROP TABLE IF EXISTS `film_language`;

DROP TRIGGER IF EXISTS `check_maximum_delay`;
DROP TRIGGER IF EXISTS `check_manager_limit`;
DROP TRIGGER IF EXISTS `check_rent_count_limit`;
DROP TRIGGER IF EXISTS `check_rental_duration`;
DROP TRIGGER IF EXISTS `active_rent_check`;
DROP TRIGGER IF EXISTS  `no_rent_reserved`;

SET FOREIGN_KEY_CHECKS = 1;
